### ISSUE TITLE
Ability to stop/restart services

### ISSUE THREAD

**Issue by dbvcode** [doorbash/pm2-web#2]
Hi,
Nice project!
Is it possible/will you add the ability to stop/restart services from the interface?
I've no experience with go, but since keymetrics require a LOT of money for one extra process that I need, I'd offer to help out with your project on the web interface side of things.

Cheers

**Comment by doorbash** [comment]
Hi @dbvcode 

I've just added support for `start`, `stop`, `restart` in go:
https://github.com/doorbash/pm2-web/compare/start-stop-restart

You can now do your thing on the web interface side :)

**Comment by doorbash** [comment]
`/command?op=[start, stop, restart]&id=[app id]`

Here is an example for stopping process with id 1000:
`/command?op=stop&id=1000`

**Comment by dbvcode** [comment]
Cheers,
Pull request sent. Kept the update to a minimum.

**Comment by doorbash** [comment]
I've just merged the PR and made some minor changes to it myself.
Thanks @dbvcode
