### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by SOVLOOKUP** [doorbash/pm2-web#4]
1. Upload a zip file from the web to deploy a new project
2. Upload a yaml file from the web to deploy a new project

I can contribute to the project, if having API documentation.

**Comment by doorbash** [comment]
Hi @SOVLOOKUP 

This one sounds like a good feature but I like to keep the project as simple as possible.
I'm even going to make the last feature added (start,stop button) optional to be honest.
Besides that, this one also makes it less secure and more vulnerable to attackers.

But we can make this one optional too if you want to contribute PR is always open :)

**Comment by doorbash** [comment]
Hi @SOVLOOKUP

This sounds like a good feature but I like to keep the project as simple as possible.
I'm even going to make the last feature added (start,stop button) optional to be honest.
Besides that, it also makes the project less secure and more vulnerable to attackers.

But we can set this one as optional too if you want to contribute PR is always open :)
